export const CART_ACTION_TYPES = {
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
    SET_TOTAL_QUANTITY: 'SET_TOTAL_QUANTITY',
    SET_TOTAL_VALUE: 'SET_TOTAL_VALUE',
};
